// A playable singleplayer session.
//
// Generate a region, draw it, let a person build in it, run the clock, and show
// them what is happening. The simulation and the HUD are both fed from state;
// nothing here decides a rule.
//
// The clock is the only place in the client that decides when time passes. It
// issues `CMD_TICK` and nothing else, because the reducer owns what a tick
// means; a client that advanced anything itself would desync the moment a
// second client existed.

import { generateWorld } from "../engine/worldgen.js";
import { defaultOptions } from "../engine/options.js";
import { apply } from "../engine/reducer.js";
import { CMD_JOIN, CMD_TICK } from "../engine/commands.js";
import { TICKS_PER_YEAR } from "../engine/constants.js";
import { RESULT } from "../shared/protocol.js";
import "../engine/build-commands.js";
import "../engine/development.js";
import "../engine/utilities.js";
import "../engine/economy.js";
import "../engine/civic.js";
import "../engine/fire.js";
import "../engine/disasters.js";
import "../engine/traffic.js";
import "../engine/history.js";
import "../engine/quests.js";

import { createRenderer } from "./render/scene.js";
import { focusOn } from "./render/camera.js";
import { createController } from "./input/controller.js";
import { phaseOf } from "./render/time-of-day.js";
import { TIME } from "./ui/settings-model.js";
import { createHud } from "./ui/hud.js";
import { createMinimap } from "./render/minimap.js";
import { openStatistics } from "./ui/statistics.js";
import { openHelp } from "./ui/help.js";
import { createMixer } from "./audio/mixer.js";
import { cuesFor, cueForResult, streetAmbienceFor } from "./audio/audio-model.js";
import { loadQuests } from "./content.js";
import { questCatalogue, activeQuests } from "../engine/quests.js";
import { CMD_QUEST_CHOICE, CMD_SET_TAX, CMD_SET_FUNDING } from "../engine/commands.js";
import { clampRate, clampFunding } from "./ui/budget-model.js";
import { toSave, fromSave } from "../engine/save.js";
import { shouldAutosave, slotSummary, packExport, unpackImport, SLOTS } from "./storage/saves.js";
import { putSave, getSave, listSaves, available } from "./storage/db.js";
import { t, locale as currentLocale } from "./i18n.js";

const SEAT = 1;

/** Real milliseconds per game tick at each speed. Slow enough to watch, fast
 * enough that a house appears within a minute of laying a road. */
/** How long a whole day of the light cycle is, in SECONDS of wall clock.
 *
 * Ticks were the wrong clock (R2, A41): at the play speed a tick is 400 ms, so
 * 48 of them was a nineteen-second day, and at fast speed six — the sun raced
 * because the GAME sped up, and the light is scenery, not simulation. It moves
 * with the wall clock like the cars and the walker do (ruling 037's shape), and
 * it stops when the game is paused, because a paused city is a held moment.
 * Four minutes: long enough that dusk is an event, short enough that a player
 * who turns it on sees one. */
const DAY_SECONDS = 240;

const SPEEDS = [
  { labelKey: "speed.paused", ms: 0 },
  { labelKey: "speed.play", ms: 400 },
  { labelKey: "speed.fast", ms: 120 },
];

/**
 * @param given.world a region already generated by the new-game screen. Passed
 *   on rather than regenerated, so the region the player was shown and the
 *   region they play are the same object rather than the same seed.
 * @param given.onNewCity called when the player asks for a different city;
 *   `main.js` puts the new-game screen back up.
 */
export async function startGame(root, given = {}) {
  const { style = "plain", onNewCity } = given;
  // Quests are pure data and have to be read in before the first tick, or the
  // opening quest is offered a month late.
  await loadQuests();

  // Disasters ON by default in the playable game. `options.disasters` defaults
  // to false in the engine because free-build is a mode; the game the player
  // opens is not free-build.
  const options = given.options ?? {
    seed: given.seed ?? 1003,
    width: given.size ?? 64,
    height: given.size ?? 64,
    seats: 1,
    disasters: true,
    quests: true,
  };
  const world = given.world ?? generateWorld(defaultOptions(options));
  if (!world.ok) throw new Error(`generation failed: ${world.reason}`);
  const state = world.state;
  // A restored city already has its seat, and CMD_JOIN on an existing seat
  // touches `lastSeenTick` — which is hashed, so re-joining a loaded save would
  // move it away from the checksum it was saved with.
  if (!state.players.some((p) => p.seat === SEAT)) {
    apply(state, {
      type: CMD_JOIN, actor: SEAT, seat: SEAT,
      // The reducer caps and sanitises it; this only carries what was typed.
      name: given.mayorName || t("player.you"),
    });
  }

  root.innerHTML = `<canvas id="city"></canvas><div id="hud"></div>`;
  const canvas = root.querySelector("#city");
  const hudRoot = root.querySelector("#hud");

  const fit = () => {
    canvas.width = canvas.clientWidth;
    canvas.height = canvas.clientHeight;
  };
  fit();

  // The map is a control, so it takes focus like one: Tab reaches it, the
  // arrows pan it, and a screen reader is told what it is rather than meeting
  // an unlabelled canvas (§30).
  canvas.tabIndex = 0;
  canvas.setAttribute("role", "application");
  canvas.setAttribute("aria-label", t("hud.map"));

  // Before the renderer, which reads it: declared after it, this was a
  // temporal dead zone and `startGame` rejected silently, because `main.js`
  // awaited `play()` without a catch (R2).
  const stillness = given.reducedMotion === true;
  const renderer = createRenderer(canvas, state, {
    style, tier: options.tier, mode: options.mode,
    // The cars are motion too (slice 4.5's preference, wired in R2). At the
    // RENDERER, not per draw: `life` at draw time gates the pose, and a car
    // that is simulated and not drawn is still a car being simulated.
    life: stillness ? false : options.life,
    time: options.time,
    // The shop signs are drawn in the player's language (R2, A40).
    locale: currentLocale(),
  });
  focusOn(renderer.view, state.width / 2, state.height / 2);
  renderer.view.span = 28;

  let overlay;
  let speed = 1;
  /** The hour the player chose, or `auto` (spec §7.3). Default `day`. */
  // `auto` is a moving sun, which is exactly what reduced motion asks against.
  let timeSetting = stillness ? "day"
    : TIME.some((c) => c.value === given.time) ? given.time : "day";
  /** Seconds of wall clock the light cycle has run for. */
  let daySeconds = 0;
  let clock;
  let lastAutosaveTick;
  // The live state is replaced wholesale on load, so everything that holds it
  // has to be rebuilt. `current.state` is the one place that knows which city
  // is being played.
  const current = { state };

  // Audio is a PROJECTION of state, like the renderer: it is handed events and
  // numbers, it never writes, and a muted client and a loud one produce the
  // same hashes (slice 4.4's gate). The mixer is created here and unlocked on
  // the first real gesture, because a browser leaves an AudioContext suspended
  // until then.
  const audio = createMixer(given.audioSettings ?? {});
  const unlockAudio = () => audio.unlock();
  canvas.addEventListener("pointerdown", unlockAudio);
  hudRoot.addEventListener("pointerdown", unlockAudio);
  globalThis.addEventListener?.("keydown", unlockAudio);

  const controller = createController(canvas, state, renderer, {
    actor: SEAT,
    onChange: () => { hud.refresh(); minimap?.worldChanged(); },
    onPreview: (preview) => hud.setPreview(preview),
    onResult: (result) => { hud.setResult(result); audio.play(cueForResult(result)); },
    // With no build tool selected, a tap inspects. That is the design's
    // "Inspect" tool without a mode of its own to get stuck in.
    onTap: (tile) => hud.showInspection(tile),
    onSpeedToggle: () => setSpeed((speed + 1) % SPEEDS.length),
    onHelp: () => openHelp(),
    onFocusTile: (tile) => { focusOn(renderer.view, tile.x, tile.y); },
    onStatus: (key) => hud.setStatus(t(key)),
    // Street mode hides the build tools and shows the way back (slice E4).
    onMode: (mode) => hud.setCameraMode?.(mode),
  });

  // Rebuildable, because a language change has to take effect on the screen the
  // player is looking at. Everything the HUD holds is derived from state except
  // the alert list, which is lost on a rebuild — a fair trade for a rare action,
  // and the alerts return on the next tick.
  const hudOptions = {
    state,
    seat: SEAT,
    controller,
    onOverlay: (name) => { overlay = name; },
    onSpeed: () => setSpeed((speed + 1) % SPEEDS.length),
    onUndo: () => controller.undo(),
    // The way into street mode and the way back (slice E4, ruling 027).
    onStreet: () => { if (!controller.enterStreet()) hud.setStatus(t("street.noStreet")); },
    onLeaveStreet: () => controller.leaveStreet(),
    onPhoto: () => controller.enterPhoto(),
    onLeavePhoto: () => controller.leavePhoto(),
    onSavePhoto: () => savePhoto(),
    onNewCity: onNewCity && (() => { session.stop(); onNewCity(); }),
    onQuestChoice(id, option) {
      apply(state, { type: CMD_QUEST_CHOICE, actor: SEAT, id, option });
      hud.refresh();
    },
    quests: { catalogue: questCatalogue, active: () => activeQuests(state) },
    onTax(rate) {
      apply(state, { type: CMD_SET_TAX, actor: SEAT, rate: clampRate(rate) });
    },
    onFunding(service, percent) {
      apply(state, { type: CMD_SET_FUNDING, actor: SEAT, service, percent: clampFunding(percent) });
    },
    onSave: save,
    onLoad: load,
    onExport: exportSave,
    onImport: importSave,
    slots: SLOTS,
    onSettings: given.onSettings,
    onStatistics: () => openStatistics(state),
    onHelp: () => openHelp(),
    minimap: true,
  };
  let hud = createHud(hudRoot, hudOptions);

  let minimap = makeMinimap();
  function makeMinimap() {
    if (!hud.minimapCanvas) return undefined;
    return createMinimap(hud.minimapCanvas, state, renderer.view, {
      style,
      onJump: (tile) => { focusOn(renderer.view, tile.x, tile.y); hud.refresh(); },
    });
  }

  available().then((ok) => { if (!ok) hud.setStatus(t("status.noStorage")); });
  listSaves().then((rows) => hud.setSlots(rows.map((r) => r.summary)));

  function setSpeed(next) {
    speed = next;
    clearInterval(clock);
    clock = undefined;
    const { labelKey, ms } = SPEEDS[speed];
    hud.setSpeedLabel(labelKey);
    if (ms > 0) {
      clock = setInterval(() => {
        const outcome = apply(state, { type: CMD_TICK });
        hud.tick(outcome.events);
        for (const cue of cuesFor(outcome.events)) audio.play(cue);
        // Where the WALKER is standing, when they are down there (V8): a busy
        // arterial and a cul-de-sac two streets away are the same city and very
        // different places. `tiles.traffic` under their feet is hashed state,
        // so this is still a projection and a muted client stays hash-identical
        // to a loud one.
        audio.setAmbience(streetAmbienceFor(state, walkerTile(), trafficUnderWalker()));
        if (shouldAutosave(state.tick, lastAutosaveTick)) {
          lastAutosaveTick = state.tick;
          save(SLOTS.auto);
        }
      }, ms);
    }
  }
  setSpeed(1);

  // --- saving ---------------------------------------------------------------

  async function save(slot) {
    const record = {
      slot,
      savedAt: Date.now(),
      summary: slotSummary(current.state, slot, Date.now()),
      save: toSave(current.state),
    };
    const stored = await putSave(record);
    hud.setStatus(stored === undefined ? t("status.noStorage") : t("status.saved", { slot }));
    return stored !== undefined;
  }

  async function load(slot) {
    const record = await getSave(slot);
    if (!record) { hud.setStatus(t("status.slotEmpty", { slot })); return false; }
    return adopt(record.save, t("status.loaded", { slot }));
  }

  /** Swap the live city for another one.
   *
   * Everything that cached the old state has to be pointed at the new one.
   * Doing this by rebuilding the world in place, rather than by reloading the
   * page, is what lets a load keep the camera where the player left it. */
  function adopt(saveData, message) {
    const restored = fromSave(saveData);
    if (!restored.ok) { hud.setStatus(t("status.loadFailed", { reason: restored.reason })); return false; }
    // Copy field by field into the existing object: the renderer, the HUD and
    // the controller all hold a reference to it, and replacing the reference
    // would leave every one of them drawing a city that no longer exists.
    for (const key of Object.keys(state)) delete state[key];
    Object.assign(state, restored.state);
    lastAutosaveTick = undefined;
    renderer.worldChanged();
    minimap?.worldChanged();
    hud.refresh();
    hud.setStatus(message);
    return true;
  }

  function exportSave() {
    return packExport(toSave(current.state));
  }

  function importSave(text) {
    const parsed = unpackImport(text);
    if (!parsed.ok) { hud.setStatus(t("status.importFailed", { reason: parsed.reason })); return false; }
    return adopt(parsed.data, t("status.imported"));
  }

  /**
   * The photo mode's one export: this frame, as a file the player keeps (F1).
   *
   * The renderer hands back a blob; the anchor is here, because a renderer that
   * reaches for `document` to make one is a renderer no test can drive. Named
   * after the city and the in-game date, so a folder of these is a record of a
   * city rather than a folder of `image (3).png`.
   */
  async function savePhoto() {
    const blob = await renderer.capture?.();
    if (!blob) { hud.setStatus(t("photo.saveFailed")); return false; }
    const stamp = `${state.cityName || "city"}-${state.tick}`.replace(/[^\w-]+/g, "-").toLowerCase();
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${stamp}.png`;
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    // Revoked on the next turn of the loop: revoking synchronously races the
    // download in some browsers and the file arrives empty.
    setTimeout(() => URL.revokeObjectURL(url), 10000);
    hud.setStatus(t("photo.saved"));
    return true;
  }

  let frame;
  let lastFrameAt = 0;
  /** The tile the walker is standing on, or `undefined` above the street. */
  function walkerTile() {
    const view = renderer.view;
    if (view.mode !== "street" || !view.eye) return undefined;
    const x = Math.floor(view.eye.x);
    const y = Math.floor(view.eye.z);
    if (x < 0 || y < 0 || x >= state.width || y >= state.height) return undefined;
    return { x, y };
  }

  /** The engine's commuter load on that tile. */
  function trafficUnderWalker() {
    const at = walkerTile();
    if (!at) return undefined;
    return state.tiles.traffic[at.y * state.width + at.x];
  }

  const loop = () => {
    // The frame delta, for the governor (ruling 040). It is measured here
    // rather than inside `draw` because `draw` is also called by gates and by
    // the screenshot harness, where wall-clock time means nothing.
    const now = performance.now();
    const frameMs = lastFrameAt > 0 ? now - lastFrameAt : 0;
    lastFrameAt = now;
    // The light cycle's own clock. Held while paused, and unaffected by the
    // game speed — the sun is scenery (R2).
    if (speed > 0) daySeconds += Math.min(frameMs, 250) / 1000;
    // Read from the HUD rather than a local: with "Auto" the overlay follows
    // the tool in hand, and no event fires when a shortcut changes the tool.
    // Whatever the camera cluster or a held key is asking for, at its rate
    // (ruling 042 §3). Before the draw, so the frame is of where the player has
    // moved to rather than where they were.
    controller.stepCamera?.(frameMs / 1000);
    renderer.draw({
      overlay: hud.overlay, frameMs, dt: frameMs / 1000, move: controller.move,
      // The clock chooses only when the player asked it to (plan.md §6).
      time: timeSetting === "auto" ? phaseOf(daySeconds, DAY_SECONDS) : timeSetting,
    });
    if (minimap && hud.minimapVisible) minimap.draw(canvas.clientWidth / canvas.clientHeight);
    frame = requestAnimationFrame(loop);
  };
  loop();

  const onResize = () => { fit(); renderer.resize(canvas.width, canvas.height); };
  globalThis.addEventListener("resize", onResize);

  // Handles for the acceptance harness, which drives this page rather than a
  // mock. A gate that tests a mock proves the mock works.
  const session = {
    state, renderer, controller,
    get hud() { return hud; },
    /** Rebuild the HUD in the current language. */
    relocalise() {
      // The old HUD's toolbars hold listeners on nodes that are about to be
      // thrown away.
      hud.dispose?.();
      minimap?.dispose();
      hud = createHud(hudRoot, hudOptions);
      minimap = makeMinimap();
      hud.setSpeedLabel(SPEEDS[speed].labelKey);
      listSaves().then((rows) => hud.setSlots(rows.map((r) => r.summary)));
    },
    save, load, exportSave, importSave,
    // What is actually DRAWN. `overlay` here is only the last callback value;
    // under "Auto" the HUD resolves it against the tool in hand and no callback
    // fires when a keyboard shortcut changes the tool.
    get overlay() { return hud.overlay; },
    audio,
    /** Settings changed: the mixer takes the new levels without a rebuild. */
    setAudioSettings(next) { audio.update(next); },
    /** The quality tier (ruling 040). Rendering only — it never reaches a
     * command. Returns whether a renderer rebuild would be needed to honour it
     * fully; antialias is a constructor argument of the WebGL context. */
    setQuality(name) { return renderer.setTier(name); },
    /** The projection (ruling 034). Shared target, yaw, pitch and span, so the
     * city does not move when it changes. */
    setProjection(mode) { return renderer.setProjection(mode); },
    /** The render style this session was built with. Changing it is a rebuild,
     * so the caller compares and restarts (R2). */
    get style() { return style; },
    /** The hour (spec §7.3). `auto` hands the game clock to the renderer one
     * preset at a time; anything else pins it. The renderer has no clock of
     * its own and must not grow one — a renderer that read `state.tick` would
     * be a renderer that could disagree with the reducer about what time it is. */
    setTime(name) {
      const wanted = TIME.some((c) => c.value === name) ? name : "day";
      // A player who asked for reduced motion does not get a cycling sun, even
      // by choosing it in the panel — the two settings would contradict.
      timeSetting = stillness && wanted === "auto" ? "day" : wanted;
      return timeSetting;
    },
    get time() { return timeSetting; },
    pause: () => setSpeed(0),
    resume: () => setSpeed(1),
    stop() {
      clearInterval(clock);
      clock = undefined;
      cancelAnimationFrame(frame);
      globalThis.removeEventListener("resize", onResize);
      controller.dispose();
      canvas.removeEventListener("pointerdown", unlockAudio);
      hudRoot.removeEventListener("pointerdown", unlockAudio);
      globalThis.removeEventListener?.("keydown", unlockAudio);
      audio.dispose();
      minimap?.dispose();
      hud.dispose?.();
      renderer.dispose();
    },
  };
  globalThis.CITY = session;
  return session;
}
