// The service worker: install once, play with the network off (slice 4.5).
//
// At the ROOT so its scope covers the whole app. Deliberately small and dumb:
// a service worker is the one piece of a web app that can brick it for a
// returning player, so it does the least it can.
//
// The precache list is `client/precache.json`, generated by
// `tools/make_precache.mjs` and kept honest by `test/pwa.test.js` — there is no
// build step, so a bundler cannot produce it at deploy time.
//
// **The version handshake.** The cache name carries the version from that file,
// which is a hash of every cached file's BYTES. So a changed byte anywhere in
// the app is a new cache, and `activate` deletes every cache that is not the
// current one. A stale client cannot half-update: it is either entirely the old
// version or entirely the new one, which is the property that matters when the
// thing being cached is a deterministic reducer (`shared/protocol.js` has the
// same argument for the wire).

const MANIFEST = "./client/precache.json";
const PREFIX = "citygrid-";

async function currentVersion() {
  const response = await fetch(MANIFEST, { cache: "no-store" });
  return response.json();
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const { version, files } = await currentVersion();
    const cache = await caches.open(PREFIX + version);
    // Individually rather than `addAll`, which rejects the whole install if a
    // single file 404s. One missing file should degrade one thing, not leave
    // the player with no offline app at all.
    await Promise.all(files.map(async (file) => {
      try {
        const response = await fetch(file, { cache: "reload" });
        if (response.ok) await cache.put(file, response);
      } catch { /* recorded by its absence: the fetch handler falls through */ }
    }));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const { version } = await currentVersion();
    const keep = PREFIX + version;
    for (const name of await caches.keys()) {
      if (name.startsWith(PREFIX) && name !== keep) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith((async () => {
    // Network first for the manifest itself, or a new deploy could never be
    // noticed: everything else is only ever replaced when the version changes,
    // and the version lives in that file.
    if (url.pathname.endsWith("precache.json")) {
      try {
        return await fetch(request, { cache: "no-store" });
      } catch {
        const cached = await caches.match(request, { ignoreSearch: true });
        if (cached) return cached;
        throw new Error("offline and no cached manifest");
      }
    }

    // Cache first for everything else. The app is a fixed set of files whose
    // identity is the version, so revalidating each one on every load would be
    // network traffic that cannot change the answer.
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(request);
    } catch {
      // A navigation that misses falls back to the shell, so a deep link
      // opened offline is the game rather than the browser's error page.
      if (request.mode === "navigate") {
        const shell = await caches.match("./index.html", { ignoreSearch: true });
        if (shell) return shell;
      }
      throw new Error(`offline and not cached: ${url.pathname}`);
    }
  })());
});
