// The Norwegian review table (slice M4).
//
//   node tools/i18n_review.mjs            writes reports/i18n-review.md
//   node tools/i18n_review.mjs --apply    reads it back into data/i18n/no.json
//
// Key parity has been enforced since slice 4.2 and it is the wrong question on
// its own: `t()` returns its own argument on a miss, so a catalogue can be
// complete and still be English. A21 has said "Norwegian is drafted, not
// reviewed" since N12 and nothing could see it.
//
// So: one table, every key, the English, the Norwegian, and **the slice that
// added it** — because a reviewer reading 414 strings needs to know which
// arrived together, and a batch from one slice usually shares a voice and a
// mistake. Kjell edits the Norwegian column; `--apply` reads it back.
//
// The round trip is the part worth being careful about. A review that has to be
// transcribed by hand is a review that gets transcribed wrongly, and a tool that
// silently drops a row it could not parse is worse than no tool — so `--apply`
// refuses the whole file if any row is malformed, and says which.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(root, "reports", "i18n-review.md");
const EN = join(root, "data", "i18n", "en.json");
const NO = join(root, "data", "i18n", "no.json");

const read = (p) => JSON.parse(readFileSync(p, "utf8"));

/**
 * Which commit first added each key, from one pass over the file's history.
 *
 * `git log -S` per key would be 414 searches over the whole history; this is
 * one `git log -p` and a scan of the added lines, oldest first, so the first
 * commit that mentions a key wins.
 */
function slicePerKey() {
  const log = execFileSync("git", [
    "log", "--reverse", "--format=%x00%h %s", "-p", "--", "data/i18n/en.json",
  ], { cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });

  const added = new Map();
  let commit = "";
  for (const line of log.split("\n")) {
    // The NUL is the format's own marker. A diff line can begin with
    // anything, a space included, so "the commit lines are the indented
    // ones" would read a context line as a commit.
    if (line.charCodeAt(0) === 0) {
      const subject = line.slice(1);
      // `<sha> slice-N12: …` → `N12`. Anything else keeps its subject: 308
      // of these strings arrived in one commit called "First version", and
      // telling a reviewer that is more use than telling them a SHA.
      const slice = /^\w+ slice-([^\s:]+)[:\s]/.exec(subject);
      commit = slice ? slice[1] : subject.replace(/^\w+ /, "").slice(0, 24);
      continue;
    }
    if (!line.startsWith("+")) continue;
    const key = /^\+\s*"([^"]+)"\s*:/.exec(line);
    if (key && !added.has(key[1])) added.set(key[1], commit);
  }
  return added;
}

/** A cell that cannot break the table: pipes and newlines escaped. */
const cell = (text) => String(text).replace(/\|/g, "\\|").replace(/\n/g, "<br>");
const uncell = (text) => text.replace(/<br>/g, "\n").replace(/\\\|/g, "|").trim();

function write() {
  const en = read(EN);
  const no = read(NO);
  const from = slicePerKey();
  const keys = Object.keys(en).sort();
  const identical = keys.filter((k) => en[k] === no[k]);

  const rows = keys.map((key) => `| \`${key}\` | ${from.get(key) ?? "—"} | ${cell(en[key])} | ${cell(no[key] ?? "")} |`);

  const body = `# Norwegian review — ${keys.length} strings

*Generated by \`node tools/i18n_review.mjs\` from \`data/i18n/\`. Edit the **Norsk** column and
run \`node tools/i18n_review.mjs --apply\` to write it back. Do not edit the key or the English:
\`--apply\` matches on the key and refuses the file if a row is malformed.*

**What to look for.** The catalogue has had key parity since slice 4.2 — every English string has
a Norwegian one — and that says nothing about whether the Norwegian is any good. ${identical.length} strings
are byte-identical to their English (they are on \`test/i18n.test.js\`'s \`SAME_IN_BOTH\` list with
a reason each); the rest were drafted and have never been read by a Norwegian speaker (A21).

The **Slice** column is the slice that first added the string. A batch from one slice usually
shares a voice, so they are worth reading together.

| Key | Slice | English | Norsk |
|---|---|---|---|
${rows.join("\n")}
`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT}`);
  console.log(`${keys.length} strings, ${identical.length} identical to their English, `
    + `${new Set([...from.values()]).size} slices`);
}

function apply() {
  const en = read(EN);
  const no = read(NO);
  const table = readFileSync(OUT, "utf8");
  const problems = [];
  const changes = [];

  for (const line of table.split("\n")) {
    if (!line.startsWith("| `")) continue;
    const parts = line.split(" | ");
    if (parts.length !== 4) { problems.push(`malformed row: ${line.slice(0, 60)}`); continue; }
    const key = parts[0].replace(/^\|\s*`|`$/g, "");
    if (!Object.hasOwn(en, key)) { problems.push(`unknown key: ${key}`); continue; }
    const value = uncell(parts[3].replace(/\|$/, ""));
    if (value.length === 0) { problems.push(`empty Norwegian for ${key}`); continue; }
    if (value !== no[key]) changes.push([key, no[key], value]);
  }

  // All or nothing. A tool that applies the rows it understood and drops the
  // rest leaves a catalogue nobody can reason about, and the reviewer would
  // have no way to tell.
  if (problems.length > 0) {
    console.error(`refusing to apply — ${problems.length} problem(s):`);
    for (const problem of problems.slice(0, 20)) console.error(`  ${problem}`);
    process.exit(1);
  }
  if (changes.length === 0) {
    console.log("no changes in the table");
    return;
  }
  for (const [key, , value] of changes) no[key] = value;
  writeFileSync(NO, `${JSON.stringify(no, undefined, 2)}\n`);
  console.log(`applied ${changes.length} change(s) to data/i18n/no.json:`);
  for (const [key, was, now] of changes.slice(0, 20)) console.log(`  ${key}: ${was} → ${now}`);
}

if (process.argv.includes("--apply")) apply();
else write();
