// Every performance card, in one table (slice D2).
//
//   node tools/perf_report.mjs   ->  reports/perf/README.md
//
// A card is one device's answer to the same nine questions. The point of the
// report is that they sit in one place and can be *read against each other* —
// and the first thing that comparison did was find a defect neither card could
// have shown alone (see the governor column, and D5).
//
// **What travels between rows and what does not.** Triangles, draw calls and
// the LOD ladder's reason are the renderer's own counts and mean the same thing
// everywhere. Frame time is the machine. And the car count is neither: the
// traffic sim fills a road at one car per frame, so a slow machine reaches a
// different city inside the same warm-up — which is why `settled` is a column
// and not a footnote.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = join(root, "reports", "perf");
const OUT = join(DIR, "README.md");

/** SwiftShader rows are the project's history, not a device. They sort last and
 * are labelled, because a table that lets a software rasteriser sit beside a
 * 4090 without saying so is a table that will be quoted wrongly. */
const isSoftware = (name) => name.startsWith("swiftshader");

async function cards() {
  const names = (await readdir(DIR)).filter((n) => n.endsWith(".json")).sort();
  const loaded = [];
  for (const name of names) {
    const card = JSON.parse(await readFile(join(DIR, name), "utf8"));
    if (card.kind !== "citygrid-perf-card") continue;
    loaded.push({ name: basename(name, ".json"), card, software: isSoftware(name) });
  }
  return [...loaded.filter((c) => !c.software), ...loaded.filter((c) => c.software)];
}

/** A column heading a person can tell apart. Four cards all headed "desktop" is
 * a table with four identical columns, which is what the first run of this
 * produced. */
const label = (entry) => entry.card.device ?? `${entry.name} (${entry.card.machine.deviceClass})`;
const cell = (text) => String(text ?? "—").replace(/\|/g, "\\|");

/** One row per sweep step, one column per card. The steps are taken from the
 * first card: a card from an older build may not have them all, and a missing
 * cell is more honest than a shifted column. */
function stepTable(entries, field, format = (v) => v) {
  const steps = entries[0].card.steps.map((s) => s.step);
  const head = `| step | ${entries.map(label).map(cell).join(" | ")} |`;
  const rule = `|---|${entries.map(() => "---").join("|")}|`;
  const rows = steps.map((step) => {
    const cells = entries.map((entry) => {
      const row = entry.card.steps.find((s) => s.step === step);
      return row === undefined ? "—" : cell(format(row[field], row, entry));
    });
    return `| ${cell(step)} | ${cells.join(" | ")} |`;
  });
  return [head, rule, ...rows].join("\n");
}

const all = await cards();
if (all.length === 0) {
  console.error(`no cards in ${DIR} — run tools/perf_card.mjs, or ?perf=1 on a device`);
  process.exit(1);
}

/** **One table per map, and never one table across maps.** A `big` card and a
 * `base` card answer the same nine questions about two different cities, and a
 * column that puts them side by side invites exactly the comparison this whole
 * lane exists to stop people making. */
const mapOf = (entry) => entry.card.map ?? "base";
const maps = [...new Set(all.map(mapOf))].sort((a, b) => (a === "base" ? -1 : b === "base" ? 1 : a.localeCompare(b)));
const entries = all.filter((e) => mapOf(e) === maps[0]);
const others = maps.slice(1).map((map) => ({ map, cards: all.filter((e) => mapOf(e) === map) }));

const machines = [
  "| card | device | class | tier | screen | DPR | build | map |",
  "|---|---|---|---|---|---|---|---|",
  ...all.map((e) => {
    const m = e.card.machine;
    return `| \`${e.name}\` | ${cell(label(e))} | ${m.deviceClass} | ${m.tier} | ${m.screen} `
      + `| ${m.devicePixelRatio} | \`${e.card.build ?? "—"}\` | ${e.card.map ?? "base"} |`;
  }),
].join("\n");

const body = `# Performance cards

*Generated by \`node tools/perf_report.mjs\` from \`reports/perf/*.json\`. Each card is one run of
\`client/debug/perf-sweep.js\` — nine views of the saturated fixture, held five seconds each — from
\`?perf=1\` on a device or \`node tools/perf_card.mjs\` here.*

**Read the columns, not the rows.** Triangles, draw calls and the ladder's reason are counted by
the renderer and mean the same thing on every machine. **Frame time is the machine**, and a
SwiftShader row is a software rasteriser in a container — it is the project's history, not a
target. The car count is neither: the traffic sim fills a road at one car per *frame*, so a slow
machine reaches a smaller city inside the same warm-up, and \`settled\` says whether the row got
to an equilibrium at all.

## The machines

${machines}

## Frame time, p50 (ms)

${stepTable(entries, "p50")}

## Frame time, p95 (ms)

${stepTable(entries, "p95")}

## Worst frame (ms)

${stepTable(entries, "worst")}

## Triangles

${stepTable(entries, "triangles", (v) => v?.toLocaleString("en-GB"))}

## Draw calls

${stepTable(entries, "drawCalls")}

## What the LOD ladder gave up

${stepTable(entries, "lod")}

## What the governor gave up

${stepTable(entries, "given")}

## Frames in the hold — did the row test the governor at all?

*Its window is 60 frames and it ignores its first 10 samples. A row below 60 did not exercise it,
and its p95 above is a percentile over that many numbers.*

${stepTable(entries, "frames", (v, row) => `${v}${row.thinSample ? " — too few" : ""}`)}

## The city each row actually measured — cars, and whether it settled

*The population is a function of simulated seconds and of nothing else (D7). Two rows are the same
city only where they have lived comparable amounts of time, which below 15 fps is **not** the same
as comparable wall-clock time — see the table under this one.*

${stepTable(entries, "cars", (v, row) => `${v?.toLocaleString("en-GB")}${row.settled === false ? " (still filling)" : ""}`)}

## Seconds of city each row actually lived through

*\`update\` clamps its delta to 1/15 s so a backgrounded tab cannot teleport anybody, so a machine
below 15 fps advances its world more slowly than the clock on the wall (Q78).*

${stepTable(entries, "simulatedS", (v) => (v === undefined ? "—" : `${v} s`))}

## The street chunk bake — chunks built on arrival, and the worst one (ms)

${stepTable(entries, "bakedChunks", (v, row) => (v > 0 ? `${v} @ ${row.worstBakeMs} ms` : "—"))}
${others.map(({ map, cards: group }) => `
## The \`${map}\` map — a different city, and not comparable to the tables above

${group[0].card.fixture}

| step | p50 | p95 | triangles | draw calls | water tris | the ladder |
|---|---|---|---|---|---|---|
${group.flatMap((entry) => entry.card.steps.map((row) => `| ${cell(row.step)}${group.length > 1 ? ` (${cell(label(entry))})` : ""} `
  + `| ${row.p50} | ${row.p95} | ${row.triangles?.toLocaleString("en-GB")} | ${row.drawCalls} `
  + `| ${row.waterTriangles ?? "—"} | ${cell(row.lod)} |`)).join("\n")}
`).join("\n")}`;

await writeFile(OUT, body);
console.log(`wrote ${OUT} — ${entries.length} card(s): ${entries.map((e) => e.name).join(", ")}`);
